language: python
python:
- '3.6'

services:
  - docker

before_install:
  - docker build -t datawig-sagemaker .
  - docker images
#  - docker run
#  - docker ps -a

script:
  - ./test/train_local.sh datawig-sagemaker
  - ./test/serve_local.sh datawig-sagemaker & sleep 10 && ./test/http_request.sh
  - docker stop $(docker ps -aq)
